global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: "minio-job"
    bearer_token: "<token>" # see docs to generate a token
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets: ["minio:9000"]
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
