name: "apps"

services:
  logto:
    image: svhd/logto:latest
    restart: unless-stopped
    entrypoint: ["sh", "-c", "npm start"]
    env_file:
      - ./secrets/logto.env
    depends_on:
      postgres:
        condition: service_healthy

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    volumes:
      - ./volumes/qbittorrent/appdata:/config
      - ./volumes/qbittorrent/downloads:/downloads
    env_file:
      - ./secrets/qbittorrent.env
    ports:
      - 6881:6881
      - 6881:6881/udp
