name: "apps"

services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    env_file:
      - ./secrets/postgres.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - ./secrets/postgres-exporter.env

  logto:
    image: svhd/logto:latest
    restart: unless-stopped
    entrypoint: ["sh", "-c", "npm start"]
    env_file:
      - ./secrets/logto.env
    depends_on:
      postgres:
        condition: service_healthy

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    volumes:
      - ./volumes/qbittorrent/appdata:/config
      - ./volumes/qbittorrent/downloads:/downloads
    env_file:
      - ./secrets/qbittorrent.env
    ports:
      - 6881:6881
      - 6881:6881/udp
